[profile.default]
# src = 'contracts'
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'tender/test/foundry'
cache = true
# block_number = 70229352
chain_id = 42161
cache_path  = 'cache_forge'

[rpc_endpoints]
arbitrum = 'https://arbitrum-mainnet.infura.io/v3/fb342284a5c7451f8fa74d9a20b81780'
